USE documents;

INSERT INTO doc_user VALUES (1, 'A', 'A@test.com', '123');
INSERT INTO doc_user VALUES (2, 'B', 'B@test.com', '123');


INSERT INTO folder VALUES
   (1,1,NULL,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'dir','testdir');
INSERT INTO parent_folder VALUES (1,"/testdir");
INSERT INTO PERMISSION VALUES (1,NULL,1,1,NULL,3);

INSERT INTO folder VALUES
   (2,1,NULL,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'dir','testdir2');
INSERT INTO parent_folder VALUES (2,"/testdir2");
INSERT INTO PERMISSION VALUES (2,NULL,2,1,NULL,3);

INSERT INTO folder VALUES
   (3,1,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'dir','testdir3');
INSERT INTO parent_folder VALUES (3,"/testdir3");
INSERT INTO PERMISSION VALUES (3,NULL,3,1,NULL,3);


INSERT INTO document VALUES (1,1,NULL,1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'txt','test');
INSERT INTO PERMISSION VALUES (4,1,NULL,1,NULL,3);
INSERT INTO doc_version VALUES (1,1,1,1,CURRENT_TIMESTAMP,NULL);

INSERT INTO document VALUES (2,1,NULL,1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'txt','test2');
INSERT INTO PERMISSION VALUES (5,2,NULL,1,NULL,3);
INSERT INTO doc_version VALUES (2,2,1,1,CURRENT_TIMESTAMP,NULL);

INSERT INTO document VALUES (3,1,1,1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'txt','test3');
INSERT INTO PERMISSION VALUES (6,3,NULL,1,NULL,3);
INSERT INTO doc_version VALUES (3,3,1,1,CURRENT_TIMESTAMP,NULL);

INSERT INTO document VALUES (4,1,2,1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'c','test3');
INSERT INTO PERMISSION VALUES (7,4,NULL,1,NULL,3);
INSERT INTO doc_version VALUES (4,4,1,1,CURRENT_TIMESTAMP,NULL);


INSERT INTO DOC_COMMENT VALUES (1,1,1,'comment test', CURRENT_TIMESTAMP);
INSERT INTO DOC_COMMENT VALUES (2,1,1,'comment test2', CURRENT_TIMESTAMP);

INSERT INTO TEAM VALUES (1,1,'test team','test team desc');

INSERT INTO USER_TEAM VALUES (1,1,1);
INSERT INTO USER_TEAM VALUES (2,1,2);